### ISSUE TITLE
100K Challenge - excessive solid Carbon Dioxide CO2

### ISSUE THREAD

**Issue by emragins** [peterhaneve/ONIMods#104]
## Expected Behavior
World should not generate with pockets of 1000kg CO2. Frozen CO2 mass should be comparable to the same area it would normally take in gaseous form.  Ie. Assuming "natural" occurrence of around 2kg/tile, doubling that (since mass is halved when dug) would give us 4kg per tile.  I would happily accept 10kg frozen chunks, but 1000kg is really excessive.

As is, these pockets honestly became the primary challenge of the map for me -- finding them and relocating the CO2 to space so that they don't instantly destroy my colony as they start to warm up.

DLC is installed but not activated.

## Current Behavior
World generates with pockets of 1000kg per tile in most biomes.

## Mod Versions
2.7.0.0 through a steam subscription

## Steps to Reproduce

1. Generate new world.
2. Observe solid CO2 pockets

## Output Log

N/A (I assume)

**Comment by peterhaneve** [comment]
The pockets of frozen carbon dioxide are set to 1000kg due to this exact issue. Larger tiles and chunks take much longer to warm up, which makes them less likely to instantly melt when uncovered, which could cause a carbon dioxide death before the player had any time at all to react.

Flaking can be an issue with these tiles causing 5kg packets to instantly sublime when exposed to warm air, but since flaking cannot be disabled (it is in the C/C++ part of the game) on 100K worlds, no workaround is available if CO2 is to be present at all.
