### ISSUE TITLE
Feature Request: Recreation while finishing up

### ISSUE THREAD

**Issue by sterlingwalsh** [peterhaneve/ONIMods#107]
Finish Up mod, dupes will congregate in a rec room and stay stationary on a cell until downtime starts

## Expected Behavior
Would be nice if dupes would be able to queue themselves for recreation tasks or even start dinner. I placed a soda fountain right where they start congregating in a rec room and no one uses it during the new block. granted, different players may use this block differently so perhaps a mod option would work well.

## Current Behavior
Playing with DLC inactive.

schedule used: work -> Finish up (1 block) -> downtime  (2 blocks) -> sleep -> bath
during the finish up block dupes move to a rec room and stay static in a cell until downtime starts.

## Mod Versions
1.3.0.0

## Steps to Reproduce
1. use schedule described above
2. have available rec room with rec building
3.
4.

## Output Log
N/A no crash

**Comment by peterhaneve** [comment]
This issue is unfortunately unfixable due to Klei's implementation of recreation chores. Recreation chores were for some reason implemented by Klei as HIGH priority (above all work chores) _with interrupt enabled_, so allowing Recreation during Finish Tasks would cause Duplicants to immediately drop their current chore and run for the jukebot. Without making another chore for every recreation building (and then doing so for every modded recreation building like Carousel), there is no way to have Duplicants safely finish a Work chore and then go to Recreation.
