### ISSUE TITLE
Fast Save Mod Feature

### ISSUE THREAD

**Issue by flyerH** [peterhaneve/ONIMods#150]
## Expected Behavior
Is a feature request, not a bug report.
Could you please add an option, save one report every 20/50/100 days instead of preserves the 20 most recent daily reports, so that you can review game changes from the beginning instead of the last few days.

**Comment by peterhaneve** [comment]
The colony reports are actually tightly coupled to numerous other game systems such as notifications, building uptime, and the resources screen. Changing them to save a report every few cycles would likely break other parts of the game.

Reducing the size of the colony reports actually has a relatively small impact on save time, and matters more on loading. Fast Save can be set to Safe to preserve all colony reports since cycle 1.
