### ISSUE TITLE
  feature request for mod NoWasteWant

### ISSUE THREAD

**Issue by Ventulus-lab** [peterhaneve/ONIMods#174]
After using your mod NoWasteWant,I have an idea.

Could you please make the mod to improve the Compost, which not only fills in Rot Pile or Polluted Dirt, but also has a freshness slider. Food below the freshness setting can also be automatically put into the  Compost for composting.

It occurs to  most players in the mid to late game automatically producing excess food.The food preservation mechanic in turn dictates that unless it is specially preserved, the freshness of many foods will drop below 50% until they spoil.It's too much of a hassle to hand select click compost for food that isn't fresh.

**Comment by peterhaneve** [comment]
If you let the food rot, it will initially become a Rot Pile which does not emit Polluted Oxygen, giving you time to Compost it before it becomes Polluted Dirt and potentially ruins your food storage. Consider using an Auto-Sweeper and Dispenser/Loader set to Rot Pile and Polluted Dirt only to automatically deliver it to compost when this occurs.

**Comment by Ventulus-lab** [comment]
Perhaps I didn't make myself clear. I know what happens to food when it rots under normal circumstances. I just really dislike food that is less than 50% fresh. Your mod allows them to be thrown out of the fridge and then either wait for them to naturally rot into Rot Pile.
@peterhaneve

**Comment by peterhaneve** [comment]
Due to the way fetch errands are batched by the game (it uses prefab ID only), making a compost accept non-rotten food could cause Duplicants to bring even fresh food to the compost if it happened to be close enough to stale food to be merged into one fetch errand. Any changes here to avoid this downside could bring noticeable performance decreases.

Consider making this request on the [Klei forums](https://forums.kleientertainment.com/forums/forum/204-oxygen-not-included-mods-and-tools/) as it is likely outside the scope of Waste Not, Want Not.

**Comment by Ventulus-lab** [comment]
Okay, then I will seek other ways to resolve it.
 I have another request for your mod "Waste Not, Want Not".There is a mod building "Freezer" that is very popular right now and is used by a lot of players.  In addition to the official building fridge, could your module also include the same freshness feature for this mod?
https://steamcommunity.com/sharedfiles/filedetails/?id=2618339179
@peterhaneve
