### ISSUE TITLE
Queue for sinks not behaving as expected with atmo suits

### ISSUE THREAD

**Issue by danielthorr** [peterhaneve/ONIMods#176]
## Expected Behavior
Either the dupes should queue up to use the sink while wearing atmo suits or they should skip using the sink altogether.
I don't own the Spaced Out DLC

## Current Behavior
My dupes are stopping to use the sink after going to the bathroom but they are not queuing up. They use it like they would in vanilla ONI, just running past the sink if it's occupied but otherwise using it like they would normally.

## Mod Versions
version: 3.5.0.0 (using mod updater)

## Steps to Reproduce
1. Get dupes to wear atmo suits
2. Get 2 (or more) dupes to touch germs.
4. Have them run past a single sink at the same time.
5. One dupe should stop to wash their hands while the other will just run past.

## Output Log
The output log was too long to fit in this ticket, so I had to upload it as an attachment. 
I don't think the log is strictly necessary in this case but for the sake of having a complete record I will include it. I also disabled all my other mods when testing this so there shouldn't be a conflict there

[Player.log](https://github.com/peterhaneve/ONIMods/files/8069202/Player.log)

**Comment by peterhaneve** [comment]
It looks like Klei reverted this behavior in update 476059, but left the target field intact on the object as dead code so it never triggered a compilation failure (as opposed to setting it to true for all sinks and wash basins). I ended up just reverting the suit logic in https://github.com/peterhaneve/ONIMods/commit/99e015707cccc2b4a9d6957787d675131b662d01 instead of checking the now-unused field.
