### ISSUE TITLE
Mod Updater Crash on Start

### ISSUE THREAD

**Issue by JoelleEmmily** [peterhaneve/ONIMods#192]
Spaced Out, main branch

Mod crashes on load when enabled. After initial crash, game enters into death loop of re-enabling mod and requiring restart.

Currently using Steam subscription. Deleted all mods from mod directory, issue persisted.

## Steps to Reproduce
Subscribe, run, enabled, restart,

[Player.log](https://github.com/peterhaneve/ONIMods/files/8259102/Player.log)
[Player-prev.log](https://github.com/peterhaneve/ONIMods/files/8259103/Player-prev.log)

**Comment by peterhaneve** [comment]
Later in your log, you have the error `Access to the path "D:/_user/Documents/Klei/OxygenNotIncluded/mods/Steam/2018291283\ModUpdateDate.dll" is denied`. Steam is trying to install the correct version of Mod Updater, but Oxygen Not Included cannot write to the saves folder. This issue is not related to Mod Updater - try the suggestions at https://forums.kleientertainment.com/klei-bug-tracker/oni/all-mods-unavailable-r31979/?tab=comments#comment-48685.
