### ISSUE TITLE
Fast Track: Desalinator playing multiple sound effects and not animating

### ISSUE THREAD

**Issue by guildcrest** [peterhaneve/ONIMods#203]
## Expected Behavior

The Desalinator should only play the activate and drain out sound once per activation/deactivation as well as should animate the fill up and drain out when throughput is less than 5kg/s

## Current Behavior

The desalinator feeding my oxygen production every five seconds (so each activation) plays the sound effect three or more times and what looks like only one frame of the activate/deactivate anim but otherwise always looks like it is running.

## Mod Versions

v2.11, I have sound batching turned off in the options

## Steps to Reproduce

1. Attach the output of a desalination to an electrolyzer
2. Watch and listen to the machine.

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/8456051/Player.log)

**Comment by peterhaneve** [comment]
This issue should be fixed in [bc0460b](https://github.com/peterhaneve/ONIMods/commit/bc0460bba5b526ef62e8e27b77d3032a311a7dd6). The Desalinator is an odd building, it waits for its 5-frame long motionless off animation to finish playing one iteration before starting other animations, but Fast Track stops looping motionless animations to avoid uploading their textures over and over for no gain. This optimization easily saves 1 ms or more per frame, but needs some special care for bad buildings like this one.
