### ISSUE TITLE
Stock Bug Fix: Conflict interests vs traits is not a bug.

### ISSUE THREAD

**Issue by Alex-1248** [peterhaneve/ONIMods#265]
Stock Bug Fix fixes conflict of interests and traits. However, a Klei developer claims this conflict is not a bug.
https://forums.kleientertainment.com/klei-bug-tracker/oni_so/plus-minus-skill-points-r27491/?do=findComment&comment=41184
It might be worth removing this fix or making it switchable.

**Comment by peterhaneve** [comment]
This bug fix was originally included in early releases of Spaced Out, when numerous obvious conflicts (such as Critter Aversion / Animal Lover) were still in the game. Since earlier base game trait conflicts such as Noodle Arms with Supply interest were forbidden, Stock Bug Fix added a change to forbid conflicts of this type as well. The new Spaced Out trait exclusions were all left blank, which was an obvious oversight at the time.

While it might be good to add an option at a later time, this bug fix will not be removed, as the developer comment is inconsistent with the earlier design philosophy of the game. Many current subscribers of this mod expect the current behavior, so any change will be opt out.
