### ISSUE TITLE
Cannot Queue Research Anymore After Hot Shots Update

### ISSUE THREAD

**Issue by nicholas-s-timelines** [peterhaneve/ONIMods#292]
## Expected Behavior

It should be able to queue researches in the Research page when shift clicking researches.

Yes, I have Spaced Out! DLC installed.

## Current Behavior

As title

## Mod Versions

`v3.3.0.0`

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/120762942/208217959-9f9ce862-f8f4-434b-ab54-daabe2a708b3.png">

## Steps to Reproduce

1. Make sure you have the Hot Shots update installed
2. Open the game
3. Load a save
4. Try to queue a research with shift clicking

Nothing happens...

## Output Log

Umm... Sorry... Could not provide you one. Sorry.

**Comment by peterhaneve** [comment]
A recent bug introduced into the base game causes the mods menu to frequently lie about the installed version. Without an output log, there is no way to truly debug the issue.

Mod Updater, unlike Mod Manager, now handles this case. Try forcing an update with that mod instead of Mod Manager, as Steam does not auto-update mods.

**Comment by nicholas-s-timelines** [comment]
Thanks! Got the Mod Updater now! I am amazed at not only it works with Mod Manager and it also integrate with the MM so well!
