### ISSUE TITLE
[Airlock Door] (possible bug) assumed top priority for stressed destructive dupes

### ISSUE THREAD

**Issue by Sgt-Nukem** [peterhaneve/ONIMods#339]
I made the observation over some hundred cycles and tens of savegames that dupes with the "destructive" stress response will always prioritize lashing out at the Airlock Door (if there is any).

Before installing this mod they seemed to go for a random tile or building, but nowadays they always go for the Airlock Doors.

Is this an intended mechanic or an oversight?
If the former - can we have a config switch to toggle that?

(BTW there is no tantrum animation to play, too. They're just standing inside the airlock until its health drops to zero.)

**Comment by peterhaneve** [comment]
The Airlock Door counts as a 3x2 of walls for the purposes of the Destructive chore, which also happens to be traversable (normally you cannot walk through walls). Since there are six target tiles which can each be accessed from either side, this puts it into the pool a whopping twelve times! It is thus very likely to be chosen, even though it is not explicitly designed in this way.

Unfortunately, the Destructive chore does not check if the tiles are part of a composite building to remove duplication (in the base game, Mechanized Airlocks and Manual Airlocks are more likely to be targeted as they are 1x2, but only slightly so) and the required information is not even available to the chore to make the decision. It would be difficult or impossible to patch the game in a portable way that would not crash on other multi-tile mods.
