### ISSUE TITLE
Fast Track cause Chore Loops

### ISSUE THREAD

**Issue by SanchozzDeponianin** [peterhaneve/ONIMods#343]
Release branch U46-552078
Spaced Out! DLC installed and enabled

## Expected Behavior

No Chore Loops

## Current Behavior

A couple of people contacted me. Allegedly, one of my mods causes a Chore loops.
I was not able to reproduce the problem right away . But then I noticed that when loading the save file of these people, a Fast Track is mentioned in the log.
A more thorough examination showed that the problem is related to Fast Track and Chore Optimization.
I also managed to reproduce the problem in just a game with a Fast Track, and my and other mods completely disabled.
[Video with an example of a Chore loop](https://youtu.be/XibKHRB6aqU)

## Mod Versions
local copy Fast Track 0.10.12.0

## Steps to Reproduce

1. Fast Track with enabled Chore Optimization
2. Duplicant with 100% Full Bladder
3. and equipped with a Suit with Oxygen less than 25%
4. Toilet (any type)
5. Suit Dock (without a suit) + Suit Checkpoint (or alternatively [Suit Recharger](https://steamcommunity.com/sharedfiles/filedetails/?id=2688074001))
6. Use the move to command to force the Duplicant to stand on the toilet cell.
7. Unselect the Duplicant.
8. Observe the loop.
The loop continues until the Duplicant is unselected.

I attach two test save files. with a Dock and with Recharger.
[Test-Loop.zip](https://github.com/peterhaneve/ONIMods/files/11192144/Test-Loop.zip)

Of course, the confluence of circumstances leading to a loop seems quite specific and unlikely. Nevertheless, somehow sometimes it happens to people in the course of a normal game.

Presumably, the problem may be related to the peculiarities of the priority values of some ChoreTypes. for example
Pee.priority == 9300 is bigger than ReturnSuitUrgent.priority == 8150
but Pee.interruptPriority == 98900 is less than ReturnSuitUrgent.interruptPriority == 99200
But I'm not sure

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/11191596/Player.log)

**Comment by peterhaneve** [comment]
Believe it or not, the base game actually has a bug in this regard - it is a "Heisenbug" as it only manifests when the chore panel of a building or Duplicant is open! In these cases, the chore prioritization is actually evaluated *differently* than when no info panels are open, which causes unusual behavior like dozens of Duplicants suddenly picking up an Attack order that had been untouched for half an hour when the chore panel of an entirely different building is opened.

Due to bugs like this, the chore actually chosen by a Duplicant when no info panels are open can sometimes depend on your machine's CPU load and memory layout (yes!). Nevertheless, even though your save does not actually cause a chore loop on my machine, I was finally able to zero in on the difference with the (broken) vanilla chore logic and make yet another hack workaround to restore the vanilla behavior in Fast Track.

**Comment by Carterpersall** [comment]
I actually experience something similar with Fast Track installed with sinks that I think is related to the Queue for Sinks mod. A dupe will rarely get stuck in a loop where they are trying to use the sink, but never do. This causes the dupe to stand in that spot, looping a 'surprised' animation until the sink is deconstructed (even starvation doesn't break the loop). I haven't been able to record the issue nor troubleshoot it a large amount though due to it being very rare.
