### ISSUE TITLE
Airlock Door temperature errors

### ISSUE THREAD

**Issue by laureolus** [peterhaneve/ONIMods#348]
## Current Behavior
Building the door always seems to result in it generating a random burst of heat, sending the door to 200+c. 

## Mod Versions
The latest steam copy.

## Steps to Reproduce

Build Door in a normal(20c ish) area
Let Dupes use it
???
Door somehow overheats

## Output Log
No crashes at least.

**Comment by peterhaneve** [comment]
The Airlock Door has very good thermal conductivity to Duplicants *and the items they are carrying*, as solids inside solids receive a 200x (not 200%, 200x!) bonus to heat transfer. If your Duplicants carry hot items such as Igneous Rock from a Volcano through the airlock, large spikes of heat will occur as the normal 75% penalty that items receive to heat transfer changes to a 200x bonus, an *eight hundred times* difference in total.

Unfortunately, the Sim is very difficult to mod to change this behavior, and doing so would break other builds that rely on the current multipliers. However, the 200x bonus also applies to buildings inside the Airlock Door. Consider running a radiant cooling pipe through it; the effectiveness will be very high due to the bonus multiplier.
