### ISSUE TITLE
FastTrack compatibility with Delivery Temperature Limit mod

### ISSUE THREAD

**Issue by llunak** [peterhaneve/ONIMods#378]
Hello, I am the developer of Delivery Temperature Mod [[*]](https://steamcommunity.com/sharedfiles/filedetails/?id=2963257205), and I would like to consult how to best make the mods work together.

My mod basically adds a temperature range check to fetch errands, and it needs to patch several places [[*]](https://github.com/llunak/oni-deliverytemperaturelimit/blob/master/Source/Patch.cs) to do that, whenever fetches/sweeps are matched or grouped. FastTrack's ChoreOpts, FastUpdatePickups and PickupOpts are options that possibly replace relevant game code. Those could be simply disabled for use with my mod, but if I understand it correctly that the BrainScheduler cost in the metrics is primarily reduced by these options, then I don't want to merely disable the options because BrainScheduler is the largest cost I see.

Looking at FastTrack code, I see ChoreComparator.CheckFetchChore() that needs adjusting. I actually don't see anything relevant for the two Pickup options, do those not affect how pickups are actually selected or am I missing some code?

Should I simply patch your functions, or is there a different way you'd prefer? I see the mod already has a number of compatibility options, although most of them seem to simply disable relevant code rather than making it work also with affected mods.

Thank you.

**Comment by peterhaneve** [comment]
Fast Track completely rewrites the entire fetch system, as the existing system is extremely inefficient. Not all of the base game methods that you patch even have equivalents any more in the new code, and some of them now run on alternative threads that cannot do the things that your code hopes to do as Unity only allows access to components on the main thread. It does incorporate compatibility deep in its code for a few mods, like Efficient Supply and Stock Bug Fix.

From a quick look at your code, it looks like any compatibility would have to be written into Fast Track explicitly, as there is no shared code path between the base game and mod. On the plus side, since Fast Track has a complete from-source reimplementation of the fetch system, many of the changes are probably easier to add as source than transpiling. However, this will also require changing Fast Track for every change in your mod, and vice versa.

**Comment by llunak** [comment]
Actually in practice it looks like patching ChoreComparator.CheckFetchChore()  is all that the mod needs so far, so I'll go with patching that and see how it goes.
