### ISSUE TITLE
No longer working after latest update

### ISSUE THREAD

**Issue by SteveFelker** [peterhaneve/ONIMods#392]
Game crashes on boot if this mod is enabled.  Was affecting vanilla game prior to "Song of the Moo" update (not sure for how long, I just starting playing again in July), and following update, Spaced out is now also crashing on boot.  Playing without this mod is painful, so hoping you can get it updated for us!

Thanks,
Steve

**Comment by peterhaneve** [comment]
Please fill out the template. There is no information here about which mod is failing, the output log, or any versions, and it will thus be completely impossible to suggest anything.

The most likely circumstances, however, can all be fixed with [Mod Updater](https://steamcommunity.com/sharedfiles/filedetails/?id=2018291283).

**Comment by SteveFelker** [comment]
Apologies Peter.  I assumed if I created the issue in the folder of the mod, it would identify it.  I will create a new issue.
Steve

    On Sunday, August 13, 2023 at 09:25:41 PM MST, Peter Han ***@***.***> wrote:  
 
 


Please fill out the template. There is no information here about which mod is failing, the output log, or any versions, and it will thus be completely impossible to suggest anything.

The most likely circumstances, however, can all be fixed with Mod Updater.
