### ISSUE TITLE
auto sweeper won't use pitcher pump / bottle emptier setup

### ISSUE THREAD

**Issue by randomfigures** [peterhaneve/ONIMods#397]
## Expected Behavior
niobium tamer setup (DLC activated, no test branch or anything)
pitcher pump in the liquid niobium right besides a bottle emptier (auto bottle activated) and above in reach of both an auto sweeper which is supposed to use the pump into the emptier so the liquid gets into the steam chamber
this is seemingly expected vanilla oni behaviour (see Francis John Ep 28 of his newest ONI-playthrough at 14:30)

https://youtu.be/uxIfiSRzZbI?feature=shared&t=870

once I deactivated fast track it worked. after reenabling fast track it did not anymore

Edit: I went ahead and did further testing by deactivating all other mods: still no interaction
I tried disabling some of the mods options, especially building options: still no interaction

## Current Behavior
auto sweeper doesn't interact with pump and empiter

## Mod Versions
local version 0.12.0.0

## Steps to Reproduce

1. try said setup

## Output Log
game does not crash. the above interaction does not take place is all but here is the Log anyways
[Player.log](https://github.com/peterhaneve/ONIMods/files/12447589/Player.log)

**Comment by peterhaneve** [comment]
I cannot reproduce the issue you have described; Auto-Sweepers with Fast Track can move liquid in this way even with Fast Track enabled:
![image](https://github.com/peterhaneve/ONIMods/assets/29011570/327f2845-c9e2-40b1-ba57-0999c9be60f5)

This issue could be specific to your computer (in which case debugging it will be practically impossible), or might be due to a different build layout. Note that Auto-Sweepers being able to move liquids at all is a bug in the base game; only molten metals are movable due to them accidentally having the RefinedMetal tag in the elements list, and the pitcher pump is not supposed to be accessible by non-Duplicants (but the sweeper can see it anyways due to a missing tag on the building storage).
