### ISSUE TITLE
Potential FastTrack crash

### ISSUE THREAD

**Issue by jenden0** [peterhaneve/ONIMods#400]
I got a crash that implicated FastTrack. The PipeFlowOverlay mod was also implicated, and I can't tell from the logs which is more likely so I'm filing an issue with both. I was working on fixing my nuclear reactor piping when the crash occurred, deconstructing/constructing multiple pipes and conduction panels

## Expected Behavior
Game should not crash
Latest stable release with Spaced Out on Linux

## Current Behavior
Game crashes

## Mod Versions
Local copy of FastTrack 0.12.1.0

## Steps to Reproduce
Unknown

## Output Log
[Player.log](https://github.com/peterhaneve/ONIMods/files/12568109/Player.log)

**Comment by peterhaneve** [comment]
Due to bugs in the crash reporter, all crashes will blame Fast Track and possibly Pipe Flow Overlay no matter the real cause.

Unfortunately, with no reproduction steps, it will be nearly impossible to get anywhere on a potential crash. The stack trace implicates a complex fabricator like a refinery or exosuit forge, and nothing related to a reactor or piping. It is likely that neither Fast Track nor Pipe Flow Overlay is actually at fault.

Recent changes to the appearance system to support skins sometimes cause problems specific to the skins that a user has unlocked, which short of hacking the skin system is actually impossible to reproduce or fix.
