### ISSUE TITLE
Fast Track "Reduce Debris Check" changes Auto-Sweeper behavior

### ISSUE THREAD

**Issue by hima2nd** [peterhaneve/ONIMods#417]
## Expected Behavior
Auto-Sweeper can retrieve molten metals from the Pitcher Pump.

## Current Behavior
When FastTrack's "Reduce Debris Checks" is enable, Auto-Sweeper can't retrieve molten metals

## Mod Versions
0.12.3.0

## Steps to Reproduce
![build](https://github.com/peterhaneve/ONIMods/assets/25268027/f878ceb3-1547-460e-a682-3284befe4111)
1.Create image builds.(using molten gold)
2.Confirm that it work when Fast Track is disable.
3.Confirm that it don't work when Fast Track is enabled and "Reduce Debris Checks" is enable.
4.Confirm that it work when  Fast Track is enabled and "Reduce Debris Checks" is disable.

**Comment by peterhaneve** [comment]
I was unable to reproduce either issue: with the exact same build, sweepers exhibited the proper behavior no matter whether the setting was on or off.
![image](https://github.com/peterhaneve/ONIMods/assets/29011570/5202035c-b588-4cbd-8d46-130b3f5d9e42)

Nevertheless, I have turned off fast chore collection for sweepers, since it might cause unexpected behavior and had a negligible performance gain for them.

The second issue seems likely to be a mod incompatibility, potentially with a mod like Partitioned Storage.

**Comment by peterhaneve** [comment]
I was finally able to track this down - if there were no living Duplicants at all in a save, Fast Track would stop updating Auto-Sweepers. Although this cannot happen in a normal game, I added a sandbox only task to update Auto-Sweepers even if no Duplicants remain.
