### ISSUE TITLE
Mods not updated on the workshop?

### ISSUE THREAD

**Issue by tomaszkrysinski** [peterhaneve/ONIMods#444]
I surmised from the comments that you have stopped updating your mods on the workshop. If you don't mind - what is the reason?

**Comment by peterhaneve** [comment]
Many mods on the workshop simply do not need to be updated after every patch. Since last October, a serious base game bug was introduced that downloaded outdated mods every more often; the game does not actually auto-update mods, so these comments probably come from users who have not yet installed Mod Updater.
