### ISSUE TITLE
Incorrect kcal amount for nosh sprout (Food Supply Tooltip)

### ISSUE THREAD

**Issue by llunak** [peterhaneve/ONIMods#445]
When clicking on a domesticated nosh sprout, the food supply information claims that it provides 51 kcalc/cycle as tofu, but that is incorrect. 21 cycles to provide 12 nosh beans, 6 are needed for one tofu to get 3600 kcal: 12/6*3600/21 = ~343 kcal/cycle.

The mistake does not appear to be missing that 6 nosh beans are needed, as in that case the number would be 57, not 51. Also, there is information about using it to create liceloaf, which is strange, as I don't see how a nosh bean could be converted to either liceloaf or water. Unless that counts converting it to dirt and fertilizing, in which case maybe the tofu value is for turning the nosh beans to dirt for fertilizing the nosh sprout, which is nonsense to do.

BTW, you also have a PR from me, in case you don't watch those.

**Comment by peterhaneve** [comment]
The new Brackene chain and dehydrated foods are confusing the mod, because Nosh Beans can technically be plant pulverized into Brackene, then sent through the Brackwax Gleaner and eventually turned into things like Dirt, Water and so forth (which is why Mush Bar appears on the list).

Blacklisting Brackene and dehydrated foods as an ingredient appears to be the best fix to prevent this loop.
