### ISSUE TITLE
Repeated crash to desktop 

### ISSUE THREAD

**Issue by Criticopulus** [peterhaneve/ONIMods#447]
## Expected Behavior
 I run the latest stable version of Spaced Out. Trouble is, I also have a metric fuck-ton of mods enabled so I don't know if the problem is due to some weird mod interactions.

## Current Behavior
Repeated crash to desktop during normal gameplay with the game flagging and disabling Fast Track as the culprit. There seems to be something related to Fast Track in the log as well.
[Player.log](https://github.com/peterhaneve/ONIMods/files/14384871/Player.log)

## Mod Versions

Latest Fast Track version from GitHub.

## Steps to Reproduce

1.I have not managed to identify the source of the bug. Hoping the log has some clues but I have no idea what any of that gibberish means...
2.
3.
4.

## Output Log

[Player.log](https://github.com/peterhaneve/ONIMods/files/14384847/Player.log)

**Comment by peterhaneve** [comment]
The actual crash is being caused by another mod:
```
[11:48:45.312] [1] [ERROR] 240, 10, 0, 0
```
There is error log spam from multiple sources (including warnings from Fast Track), but the actual cause is another mod. Unfortunately, the error message does not include the source mod, and bugs in the crash reporter mean Fast Track will be blamed for _every_ crash regardless of cause.
