### ISSUE TITLE
Crash with Fast Track mod

### ISSUE THREAD

**Issue by Kassean** [peterhaneve/ONIMods#510]
The rocket should land and take off.

I have the Spaced Out! DLC and Frosty Planet pack installed

Crash on rocket landing/explosion caused by Fast Track mod. The crash doesn't always happen, when loading from the same point the next time the crash may not happen (I started making a save before landings and takeoffs!).

FastTrack_0.14.0.0

## Steps to Reproduce

1. The rocket lands by itself when it arrives, or press the “land” button on the rocket platform. Similarly with takeoff

## Output Log
[Player.log](https://github.com/user-attachments/files/16784621/Player.log)
![image](https://github.com/user-attachments/assets/cd558674-d062-41c1-8a7d-ca9681c3ea76)

**Comment by peterhaneve** [comment]
There is no Fast Track code in this crash. The base game will blame Fast Track for every single crash due to bugs in the crash reporter, even when it is not at fault.

It may be a compatibility issue with another mod - if you can identify a setting to disable that works around the crash ("Side Screen Optimizations" is my first guess) then it may be possible to add a workaround.

**Comment by Kassean** [comment]
The error appeared when i put a slamming door under the control station to pump the pilot skill constantly, even when the door was forcibly disabled the error reappeared. i removed the door, replacing it with a simple cage and the error stopped appearing. without Fast track i didn't check for the error
