### ISSUE TITLE
Partitioned Storage Crash?

### ISSUE THREAD

**Issue by Kassean** [peterhaneve/ONIMods#515]
I don't understand what's happening and why. I'm just playing, after loading from the same place the game ends in a minute or two. I don't understand the reason. the game blames FastTrack, but I'm not sure it's to blame

## Expected Behavior
 just playing.
 2 DLC

## Current Behavior
 Crash

## Mod Versions
 local copy Fast Track. game - Steam
 

## Steps to Reproduce
 just playing

## Output Log

[Player.log](https://github.com/user-attachments/files/17016987/Player.log)

**Comment by peterhaneve** [comment]
The log shows `Invalid amount: 0` which can only be printed (by the base game) in `FetchAreaChore.StatesInstance.Reservation` when an invalid amount is reserved for a storage chore. I would report this crash (ideally reproduce it with Fast Track disabled) to the author of [Partitioned Storage](https://github.com/kat0r/oni_mods/issues) as that is almost certainly the cause.

Due to bugs in the base game crash reporter, Fast Track will _always_ be blamed no matter which mod crashes.

**Comment by Kassean** [comment]
> The log shows `Invalid amount: 0` which can only be printed (by the base game) in `FetchAreaChore.StatesInstance.Reservation` when an invalid amount is reserved for a storage chore. I would report this crash (ideally reproduce it with Fast Track disabled) to the author of [Partitioned Storage](https://github.com/kat0r/oni_mods/issues) as that is almost certainly the cause.
> 
> Due to bugs in the base game crash reporter, Fast Track will _always_ be blamed no matter which mod crashes.

I configured only once this storage and everything worked correctly until a certain point, I did not change the settings of the storage. the crash happens in the same place and with FastTrack disabled. The only thing that helped me was to completely uninstall the mod Partitioned Storage to make it stop
