### ISSUE TITLE
[Stock Bug Fix] Bug: harvestable plants stop consuming resources

### ISSUE THREAD

**Issue by Sad-theFaceless** [peterhaneve/ONIMods#517]
Here it is, I thought Klei finally implemented it as a feature, but it was a bug from Stock Bug Fix all along... I loved this, but I dislike it more when my game has a bug that vanilla doesn't have, so I volunteer myself to be the bad guy reporting it T_T

## Expected Behavior

Harvestable plants continue to consume fertilizer and irrigation.

## Current Behavior

As the title says, having Stock Bug Fix enabled causes plants to stop using irrigation/fertilizer once they're grown up.

I suspect this is caused by [this fix](https://github.com/peterhaneve/ONIMods/blob/main/StockBugFix/PlantIrrigationFixPatches.cs).

## Mod Versions

V4.2.0.0
Updated mod from the Steam's workshop, I have Mod Updater, too.

**Comment by peterhaneve** [comment]
This behavior is taken from the *Better Farming Effects and Tweaks* mod. It is by design - plants that are not growing in the base game (including, in some cases, plants stifled by lack of atmosphere etc) would _sometimes_ still waste fertilizer and irrigation even when no progress was being made. In order to fix this bug and disable consumption when not growing, the fully grown state must also be included as the plant is not growing.

This fix also allows additional improvements such as *Farmers and their insect friends will not try to accelerate the growth of wilted or non-growing plants, including fully grown plants, sleeping Gas Grass and the hungry Saturn Critter Trap.*

**Comment by peterhaneve** [comment]
An option to turn this behavior off has been added to Stock Bug Fix if this bug is important to your colony.
