### ISSUE TITLE
Game crashes when unpausing after load

### ISSUE THREAD

**Issue by kstathem** [peterhaneve/ONIMods#522]
The game loads with no mods, crashes with only this one.

## Expected Behavior

Spaced Out is installed but turned off, Frosty Planet is on.

## Current Behavior

Crashes as soon as I unpause the game.

## Mod Versions

Steam subscription, and yes I have done a force update (v2.6.0.0). I have also tried switching to a local copy (which is v2.5.0.0) and it does not crash.

## Steps to Reproduce

1. Load the included save with v2.6.0.0 of  this mod from steam
[The Lunar Utopia.sav.zip](https://github.com/user-attachments/files/17680354/The.Lunar.Utopia.sav.zip)
2. Unpause

## Output Log

[Player.log](https://github.com/user-attachments/files/17680314/Player.log)

**Comment by peterhaneve** [comment]
Workshop Profiles has been updated again to version 2.7. Due to how mod updating only works if the game can successfully reach the main menu, popular mods need to be updated for Public Testing silently before it goes live, or else all users will be stuck on a crashing version unable to get to the Mods menu to check for updates.

There is no stable mod API, and the most recent Public Testing branch fully rewrote several core game systems. It looks like one reference slipped through when trying to make Workshop Profiles dual-load, but this should be resolved.
