### ISSUE TITLE
REQUEST: Stock Bug Fix - Allow Store Equipment chore type selection between Supply/Store

### ISSUE THREAD

**Issue by BeamupSTC** [peterhaneve/ONIMods#530]
Currently, Stock Bug Fix allows users to choose whether the Store Food errand will be considered Supplying, or Storing.  The same choice would be valuable for the Store Equipment errand, for the same reasons.  I suspect this would require only duplication and slight edits of the existing code for Store Food in StockBugsPatches.cs and StockBugFixOptions.cs so a very small effort?

**Comment by peterhaneve** [comment]
Unlike storing food which is clearly not a Supply errand, Store Equipment is only used for dispensing new Pajamas and putting suits into a locker. Putting Atmo Suits into a Suit Locker is pretty clearly a Supply errand as the suits are used for operation, not just stockpiled, and storing Atmo Suits into storage bins or tiles uses the correct Store priority.

Stock Bug Fix adds an option for Store Food because it is used for putting Food into a Refrigerator, which is clearly a Storage errand, but is wrongly classified by the base game as Supply. The option allows users who were dependent on the broken behavior to switch this fix off for mature colonies. I do not believe that Store Equipment should be reclassified as a Storage errand as it currently stands, although if Klei adds a storage closet for items like Warm Vests it might be worth revisiting in the future.

**Comment by peterhaneve** [comment]
Since adding more options rapidly explodes the testing matrix for this mod, Store Equipment in future releases will now share the same choice as Store Food. The option text will be updated when this change is made.
