### ISSUE TITLE
Suggestion: Add manual override for Airlock Door mod

### ISSUE THREAD

**Issue by G-M-twostay** [peterhaneve/ONIMods#531]
Is it possible to add a manual control for the airlock door mod? Currently building the power wire before the door can be quite tedious and duplicants getting stuck when unpowered is bothersome to deal with. I'm thinking that when operating unpowered, the door will open and close slower like mechanical airlock while liquid/gas sealing won't work (since no power).

Many have came up with this suggestion as comments on the steam workshop page, but since you don't read them I decided to put a suggestion here.

**Comment by peterhaneve** [comment]
Due to how the base game implements gas and liquid sealing, disabling sealing will be impossible while unpowered, which makes it a bit cheaty if someone is willing to wait. An attempted workaround with the offset tracker to allow Duplicants to "reach inside" even when closed caused an unacceptable performance penalty.

There may be another workaround yet but it will be a lot of work to rewrite a good chunk of the mod. Will consider looking at it again after the Bionic Booster Pack has been out for a bit.

**Comment by peterhaneve** [comment]
I took a different approach and allowed building the wire after the Door in a different way. Try it out with the latest version!
