### ISSUE TITLE
Duplicants randomly getting entombed when passing through Airlock

### ISSUE THREAD

**Issue by Draxial** [peterhaneve/ONIMods#59]
Duplicants somehow get stuck and entombed behind the power meter in the airlock; maybe when it is charging somehow the graphics changing puts a tile there and makes them entombed?

## Expected Behavior
Duplicants shouldn't get entombed

## Current Behavior
Duplicants getting entombed

## Mod Versions
Steam subscription, tried force update already; 1.2

## Steps to Reproduce
I don't actually know. I randomly get alerts with them getting entombed, once each 20-50 cycles or so. Thankfully they disentomb sometime later.

![image](https://user-images.githubusercontent.com/53184989/83956408-21611e00-a834-11ea-92e3-d839b124a289.png)

**Comment by peterhaneve** [comment]
For airlocks that are used very heavily, the internal power bar (as is shown in the picture) may deplete too quickly to be recharged. While the current operation is allowed to complete without withdrawing more energy, if the Duplicant decides to turn around and go back (due to downtime, chore cancelled, and so forth) entombment can occur. A similar issue will plague transit tube entrances that are used too heavily.

Consider allowing multiple paths through different airlocks to allow the airlock more time to recharge.
