### ISSUE TITLE
Claustrophobia: Confined false alert

### ISSUE THREAD

**Issue by jmucchiello** [peterhaneve/ONIMods#73]
When a dupe idles on the atmosuit square where dupes put on/take off atmosuits, dupes beyond the atmosuit checkpoint will be considered confined and cause a false alert.

## Expected Behavior
No alert

## Current Behavior
An alert pauses the game.

## Steps to Reproduce

1. Build an atmosuit dock.
2. Send several dupes beyond the checkpoint.
3. Have one dupe return from the beyond area with no pending tasks so they will idle at the checkpoint.
4. Alert.

## Output Log
There are no errors

**Comment by peterhaneve** [comment]
I am unable to reproduce this issue, as no alert is triggered in this exact setup https://imgur.com/a/C4GWfyg. Consider using Show Navigation on the Duplicants that are beyond the checkpoint to see if they are actually unable to pass, as they may be prohibited from returning due to having no place to store the suit in the station.

**Comment by jmucchiello** [comment]
No, this happens on bases with only one dock with no spare suits in existence.

I've never been able to reproduce this consistently. I should have mentioned it is intermittent. I've tried recreating it in sandbox with no success.
